---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2023.5.3
    env:
      TZ: "Europe/London"
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${HASS_LB}
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "home-assistant"
        hosts:
        - host: ${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - ${SECRET_DOMAIN}
    prometheus:
      serviceMonitor:
        enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-pvc
    postgresql:
      enabled: true
      image:
        repository: postgres
        tag: '14.4'
      auth:
        database: home-assistant
        username: home-assistant
        password: "${HASS_POSTGRESQL_PASSWORD}"
        postgresPassword: "${HASS_POSTGRESQL_PASSWORD}"
      primary:
        persistence:
          enabled: true
          existingClaim: home-assistant-postgres-pvc
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.10.1
        workingDir: "/config"
        args:
        - --auth
        - "none"
        - --user-data-dir
        - "/config/.vscode"
        - --extensions-dir
        - "/config/.vscode"
        env:
          TZ: "Europe/London"
        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            ingress.kubernetes.io/whitelist-source-range: 192.168.167.0/24
            nginx.ingress.kubernetes.io/auth-url: https://auth.${SECRET_DOMAIN}/oauth2/auth
            nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/oauth2/start
            hajimari.io/enable: "true"
            hajimari.io/icon: "microsoft-visual-studio-code"
          hosts:
          - host: hass-vs.${SECRET_DOMAIN}
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - hass-vs.${SECRET_DOMAIN}
        volumeMounts:
        - name: config
          mountPath: /config
        # - name: deploykey
        #   mountPath: /root/.ssh/id_rsa
        #   subPath: id_rsa
    resources:
      requests:
        cpu: 500m
        memory: 300Mi
      limits:
        memory: 500Mi
