apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: networking
stringData:
    TS_AUTH_KEY: ENC[AES256_GCM,data:kvuaO37DldqpSdp6lvwAkOuDKNyuR5JK1EPyliTbBhYdxaACKmElxqIFujDCvNUQaPB02k//zAE=,iv:hRJmXnullGJTS3wb/V5rAPQ5H+OBt8IP1LsZ1ac+JKE=,tag:ZkSEhMq4zvg2p+egsW5Qqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTWh2bWNjbWs5MkN1dkx1
            OWs0R0ZWVjNoRUkzTEZkbjNIak1ZWVhZd2swClJ6RTg2WGROWS8zQXpWWEUxQ0xl
            WXZiUTBzaVNqQ2phU2ZWajBjK1BSOFkKLS0tIE9EaDhMTFVlS1MwYjBCa0JRWUJG
            d0hBYVk0M2IzaTU0aHJoSFMySXFCdFEKZOocSUSww6/nBZLVu4kxNBB8j1iOiEc6
            1SeTCtjo2hHzrS+wqEzxZxQV/RbXVIiSblv7D891/sMqzgBDo0kCvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-08T21:11:54Z"
    mac: ENC[AES256_GCM,data:n/Z0kfLBJBV+l506XwzXOq313FuiTPQsuW6A3AIpXWhecEP3rlMVrwCPvt0S7r5VE8Wcz2zpTY+iC3BPpplRF6z1YU2YIu0K2P/R/nqJjsonEadbHUVdXxUs8R3pjOP8ix9SGXk0h9GJzRGHoU4dYXFiEQuzsMGwCiGhB1Vcomg=,iv:EtE9Iil2hMCIpX5bC2wzpay06KSBix5TUeYiRsFnD74=,tag:PRbj1w369usEGP82uSMbzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
