# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:fj8ysYbfbeWE73eGYuJGzFHzfPuEHpvtFF5puwpMkgazVqQRhqezx1VNYf5+VHmtAZO8DMSB8QhplyazpwD7t8VHXB9skjohqhk+Ur/TWUKaxB6/+nS45UQoKZ0MMSp2B+dd1LHupWyw/yI06yaBfwXTpEKR7S1z,iv:/HljiCwl2qQLXzo3JL3wBdERg0zy1uwXy0G4tYcXhLw=,tag:Mr90x3NoYLzscf8eG34/XQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNkJocVJRMGJUaVhwazFi
            WUdHWW5ldGRWZVFrWThLVW94aHRvTjl0MFZBCjY4ZmpSV3ByZCthZGpQYnFUOFlp
            VFJmb1ZJV2F5TjZOVm1mb3g2cFg4YjgKLS0tIGF6UW1MaXY5MHh0SVN5SWoxTnhL
            OUpibDBsaUw0RkwyV0ozUmpiZzJiMVUKy0oEEK+moNGF+cg2cPRyK6K8Sa1xtMYI
            yGdfNgIL5AaLDR0LMotKnEH75xTwK/viSYAZQVnEXoEJjLPUjICecw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-22T17:01:11Z"
    mac: ENC[AES256_GCM,data:NnpUC7gSjZKD0PtBPhI88hHYkwZDd3s1mxdJVrzTGnxt3jdxgJlV9WDzjUJV4RYnrwGplJq1MD9ghVTubYg6ojNRElxR++xc7R8wvvGu50gWmS1PvzKGLjrueaGE4OZmMInAecitllYahJez+mZjPvcy32sLGcbX7gpjoErBGFg=,iv:tjR+e8PDuDDYxgx5Me+y1WiQNlHnw4a0PxxTuo1ofWY=,tag:jihRvbJUVhvsLUMDkrhAUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
