apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - longhorn-charts.yaml
  - oauth2-proxy-charts.yaml
  - prometheus-community-charts.yaml
  - metallb-charts.yaml
  - rook-ceph-charts.yaml
  - grafana-charts.yaml