---
pxe-servers:
   hosts:
     pxe-server:
       ansible_host: 192.168.167.30
       ansible_user: ubuntu
kubernetes:
  children:
    master:
      hosts:
        k8s-hpe1:
          ansible_host: 192.168.167.21
        k8s-hpe2:
          ansible_host: 192.168.167.22
        k8s-tmp:
          ansible_host: 192.168.167.18
          ansible_user: ubuntu