---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: esphome/esphome
      tag: 2023.5.5

    env:
      TZ: "Europe/London"
      ESPHOME__INSTANCE_NAME: ESPHome
      ESPHOME__PORT: &port 6052
      ESPHOME__APPLICATION_URL: &host-cluster "esphome.${SECRET_DOMAIN}"
      ESPHOME__LOG_LEVEL: info

    # App needs to run as root because of this: https://github.com/esphome/issues/issues/2752
    securityContext:
      runAsNonRoot: false
      readOnlyRootFilesystem: false
      privileged: true
      allowPrivilegeEscalation: true

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          ingress.kubernetes.io/whitelist-source-range: 192.168.167.0/24
          nginx.ingress.kubernetes.io/auth-url: https://auth.${SECRET_DOMAIN}/oauth2/auth
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/oauth2/start
          hajimari.io/enable: "true"
          hajimari.io/icon: "car-esp"
        hosts:
          - host: &host "esphome.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: esphome-pvc

    resources:
      requests:
        memory: 250Mi
