---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 10.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.17
    replicas: 1
    timeZone: "Europe/London"
    config: |
      upstream:
        externalResolvers:
        - tcp-tls:1.0.0.1:853
        - https://cloudflare-dns.com/dns-query
        - tcp+udp:1.1.1.1
      customDNS:
         mapping:
           freenas.${SECRET_DOMAIN2}: 192.168.167.5
           ${SECRET_DOMAIN}: ${INGRESS_NGINX_LB}
           router.lan: 192.168.167.1
           k8s-nuc.lan: 192.168.167.15
           k8s-hpe1.lan: 192.168.167.16
           k8s-bt3.lan: 192.168.167.17
           k8s-hpe2.lan: 192.168.167.18
      blocking:
        blackLists:
          ads:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
          - https://mirror1.malwaredomains.com/files/justdomains
          - http://sysctl.org/cameleon/hosts
          - https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
          - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
          bad:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts
        whiteLists:
          ads:
          - https://raw.githubusercontent.com/chadmayfield/my-pihole-blocklists/master/white.list
        clientGroupsBlock:
          default:
            - ads
            - bad
      clientLookup:
        upstream: tcp+udp:192.168.167.1
      prometheus:
        enable: true
        path: /metrics
      httpPort: 4000
      logLevel: info
    service:
      main:
        ports:
          http:
            port: 4000
      dns-tcp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${BLOCKY_LB}"
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
        externalTrafficPolicy: Local
      dns-udp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${BLOCKY_LB}"
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
        externalTrafficPolicy: Local
    prometheus:
      serviceMonitor:
        enabled: true
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - blocky
          topologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        memory: 280Mi
        cpu: 50m
      limits:
        memory: 1000Mi
