# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:J6Xt0N03rBZZYbMC,iv:84AMn47hTY4GLyyzPKXLjs3poNwBlsv5Yt2nKvSXxQI=,tag:jzT6LjZUOar7cIYFvO/kgw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ZoDCg0rK5LoTh/ZUEyfAqrc=,iv:NnEmfVmviJUu/FLCUg6HQHSFZegLZZCQwM80GWxBLpU=,tag:Ue/ueqxIrQ8Bh+9BI6ZkvA==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:T18jo854TckToFeuf7OqQlKjNjdUyexISAQNOcoewRLU7hMAaUo3BYnDCo6H4+A8eOemjOGqquwjPiXL7PEWth8dlllD362y8PqcONkVpkCrcV2Vtf6g6Ac58qTnnqvHOymkAmFc7933CUuoqYJA+EaoER1LebTEcs2RhxU6,iv:7piUTvs/aH0jXeCSqdEXUF3dVgfQZ1O01mtPodf7fzs=,tag:jyeh9G/GSzo52OEyyaunXQ==,type:str]
    OAUTH2_PROXY_OIDC_ISSUER_URL: ENC[AES256_GCM,data:491KAn6FlmEQLjAkl32tg40vSpd7VOG2ZGtLETB156LvcQ==,iv:9BlvEplEtRmQc9156cLWHUqKUlTTGCbV6ndlS1R5W7M=,tag:8eCs5CTGCJyhYNNUcjUDDw==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:Ah5bWXI0kJAZVQ8SARY=,iv:nhaSGZjEGMtjimNNDqFnfwydnM6CIJoWntX6COor9QU=,tag:w02wBEl9lI42gdcMpSL5Cg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UnJnTndBRW1OWUR3TnZQ
            ZjNMT3N6OE4wZ1FQcFE3bVhoYm04djZJTHcwCnp2K1QyWGgxRHhEN0h2VWU0aTAw
            RE02TU9jc1JIOHhRQ2pyNnRkNmFBRkUKLS0tIGR5eFNFOUFNbjlicDdxWDVoVklQ
            aVExMU04b3FTM2c4UzZQTmZlM1llNk0KWdHZQOu6yN5hBWy2jxXiMqtg1W1IPBaO
            MoQ8eps7B2xrECTArP+i88bDhPPYFvskMlLvsTwUncNnLEW9qcVnaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-22T22:01:22Z"
    mac: ENC[AES256_GCM,data:giHtdLHmfM8h1k2O3qjGBHQJe+xdvPM00nMPDlU7pOKUjvSCanNCZ2PBPpfZQ954JR2+fDxq8jwWtsc9yjxVTla1RBtr2mt56fBKun21yjBzw5eugYjmPAjjOT/1ek2CuG4eLkqhtWAK5QZm4hfEfZPMc6VQVD8n0d3isak2VFw=,iv:wKfbqBLHBCNT3+LR9iHypAl8tR2ySNZyH+UoCqqMgbM=,tag:QaInNhgzQYI/ehtJcXYE8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
