---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.167.70-192.168.167.90
  INGRESS_WHITELIST_SOURCE_RANGE: 192.168.167.0/24
  INGRESS_NGINX_LB: 192.168.167.70
  BLOCKY_LB: 192.168.167.71