---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy-home
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: oauth2-proxy
      version: 5.0.7
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: quay.io/oauth2-proxy/oauth2-proxy
      tag: v7.1.3
    replicaCount: 1
    ingress:
      enabled: true
      path: /oauth2
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
      - "auth.${SECRET_DOMAIN}"
      tls:
      - hosts:
        - "auth.${SECRET_DOMAIN}"
    extraArgs:
      provider: oidc
      oidc-issuer-url: "${OAUTH2_PROXY_OIDC_ISSUER_URL}"
      skip-provider-button:
      pass-authorization-header:
      email-domain: "*"
      cookie-domain: ".${SECRET_DOMAIN}"
      whitelist-domain: ".${SECRET_DOMAIN}"
    resources:
      requests:
        memory: 10Mi
      limits:
        memory: 50Mi
  valuesFrom:
  - kind: Secret
    name: "oauth2-proxy-helm-values"