apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-helm-values
    namespace: networking
stringData:
    values.yaml: ENC[AES256_GCM,data:zp9IMYNs+0de6bWsdeLuUleiNYJoWx57ZR03CD54hfKi9YpJ1NdfOUMtaXoOXn1sYc0OnlAdXvB+Q77kfQtBUwhzcO/J3IHN+IIUQwl5rMt77xwsBkJeZJkzhFgq5dBH55AmV5+FxmNIJ3ABpscoNacBr7YsImPUC7qvJ0g9q0PXumih9K/EW+dmrYqRIxk5XejgHbaOj7FDxbca42Dk0ARMMuqAT8IaiTZQe4H3+JIT2RVx,iv:LIu8D+9lRdICLY+rbsEsNOu5ESKOZSkXOxCJ0e5ceik=,tag:+zw4aDmeK0sFgHfMjlFl2Q==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTWh2bWNjbWs5MkN1dkx1
            OWs0R0ZWVjNoRUkzTEZkbjNIak1ZWVhZd2swClJ6RTg2WGROWS8zQXpWWEUxQ0xl
            WXZiUTBzaVNqQ2phU2ZWajBjK1BSOFkKLS0tIE9EaDhMTFVlS1MwYjBCa0JRWUJG
            d0hBYVk0M2IzaTU0aHJoSFMySXFCdFEKZOocSUSww6/nBZLVu4kxNBB8j1iOiEc6
            1SeTCtjo2hHzrS+wqEzxZxQV/RbXVIiSblv7D891/sMqzgBDo0kCvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-22T16:59:44Z"
    mac: ENC[AES256_GCM,data:XL6rD77iCgmEAHp0EtY+kzaZS1DpOx1LSauHXy/M+qxZ/3ksyZVV2aUmfBPOuvLZQ65o8bkgPhXkv/xTN6IcpYWhkuGjfQfIdkVGaRKqjOKD9a6kf1xyst/Xy6Ou7AAkUphFM/w+riTIW8OJV3kC8C90ecfMy0LjUcEhjn0qBaw=,iv:s64JxVFf9h1aP4fz8I2zqKDoncP1BtQqSfuBfKcmOL4=,tag:zNWqdwRH11lHcG7XR/MUgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
