---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClassReplicaCount: 3
    defaultSettings:
      defaultReplicaCount: 3
      createDefaultDiskLabeledNodes: true
      backupTarget: s3://longhorn-prd@us-east-1/
      backupTargetCredentialSecret: longhorn-backup-secret
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        ingress.kubernetes.io/whitelist-source-range: 192.168.167.0/24
        hajimari.io/enable: "true"
        hajimari.io/icon: "server"
      host: "longhorn.${SECRET_DOMAIN}"
      tls: true
