apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: longhorn-backup-secret
    namespace: longhorn-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:8O4qrwlk8kY=,iv:zMB9AsZeDj55cZoBhj8ElufqNBOvHkhQhvyWvL8Fh2M=,tag:11Z/jR+YJGAl2a4B7Eq1wA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:EOK6VpBSpIjKrlHGeWLS49Qohtc=,iv:72RMrEGy+y8VwsjVC6f9AqZnx+yopnpM/f+GiU1tftc=,tag:BPiTgVsEYACkfBPqA1sFYA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:neLk3EsXm7FfDS5ovrNdVER3xTNgW9YDlLTP5jGmFq30,iv:vhIjm7am2mnld24UPaajehHcwbghhxybh1omtejEhUc=,tag:0VpgTpX/8x2znYcyYG793Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-18T15:13:40Z"
    mac: ENC[AES256_GCM,data:pJ5g8kMpW8jznTTAWvYzL+zgsF39lspKMxSRqHdQylizljrtl3SVixkvAq+xOvnz9PWwfbkOg4Plcm1XLw3rjSOZyoYozKVI9Mgr+LSsOnWCb+jAK2E7jDDXDo0BT/2ubd4SeHqz/dl0fyw/t2JAyq+THvp3l+K9MuxkKQSO3zk=,iv:HfIGEiJJTQ0s1geVG85xuJto/NYxFM62afTlwm9Uuws=,tag:vbBKtwWC/zi2+uGxJjkinw==,type:str]
    pgp:
        - created_at: "2021-09-18T15:13:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2AUzSsvr0dQAQ//ZcNOpBFRmWeGnrhIWEB1XJkg4yJxWB62xbtJu1pTw1x5
            jAlVrQxSjuoE3ihraZvqgswoSoAQtzXoBJWPU6DnQiaPZCCMXvV19OJY+jG5P0za
            y1S+AYF11ejgRoTp8KND+W8gLB5iywQ7hEwfOPXO4EMtfRm6pyvkT05ww2EhKXPW
            Wl/TG7rcB/w2skVEfIXrq58eODxGvy0LM9e/i0zE3hzIocmBPSS88NRc0ltOpyq6
            lqflIWfw9PrUd3gD1sgoKOMlzGrFWgqRJ2C1f3POx86I7xAJHX4Y9QVgrPA5gQz5
            lb+bhdJLrlE1mVjLUYjAbadoJKmwLg3R7gCPXjfNvD9JMW/U0Pp/Y7BOdAP30Fv7
            ukOUed0MVX8SQPBd1WW2t+hj/DJ5aVxz0/qxff9bsiIJGnuvY6pWG5oYL86Blkel
            SzUC0jbth3P8VE4+fWeNwZvcx5//OrZyPvqkJ9cvgU3rlLHfmxvFX+bNATh06bOU
            GX83of0YFyWTM9bhA0dZVJVppdTvpPZSLqDj6DiozrAixBIZp5lSLoDfYOZle5WI
            Yb21YN6hg9ninnv5IsGZV5P/W2pr5uRNssoGdVURD68p4pgElkgNJJpGriVJPGYR
            X6RAhKA7z25z8PQfNPt0ieowV9lIamUz1CJfptmcE/J3w2449B1ABEvaLcrgFn7U
            ZgEJAhVuFSYwUco4bDQokWzwhNdcublt5yjfS1KQyj6mIRrS8fYWxmOWUVR2vIya
            IfAwsbJuaN35/cyHmQ35X4pM6urYwVvR5CTZC/Qyc8beGlQCLE6kgPvMJleJNk7t
            T7KLdegutQ==
            =vwlu
            -----END PGP MESSAGE-----
          fp: DD53CFDD9A6834FBE51894EA6BDA17AA6135549F
        - created_at: "2021-09-18T15:13:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA42nrMmwcdfpAQ//XSfXK3GRuYDWjZDtn7hi8KjdrR982deFj/aglAs43wgj
            9bMMLRjj05+R1FHlJ0959bq7d75tY6WPhIj//+KBapb02MlQtTj/zBwCE7XCYsNo
            /ojrfQuOsNEFyqatMcpmudjfbjn6mrH53bM28yi08MMxqkwLt3qFoy6JySEvqkEk
            QHtOQLnY1wqaQ2T+tgC/mb+OgDKs/lqvQ4Rtk4sorl2hHd8Kt3Z6RneuQnL9ErrK
            V61trpHiZ0jKFnN4ok67v1S/u2jHu2+wH2S3wFBNOnv996B48p/cwJekqyNK5EF7
            Ox8W1/CUthJWzFKy3I9WS9bIix+galsXLx63qPTKGp7ri1gcv/f3zNue5T1kT91O
            EDB9PWXvbQe789h7HmVjkimZRLoVf6/pqG1Z4k1yoeM2hYGP/uN1Nbb7d2TmyYfl
            1D1TB1bX8RqVDtXlkaWUHi2NQFNwCa+KS+87na61orG+/scZ5hdD2nC0RfcnDhk/
            lUNXBOMHFFVlE/6DynI1wrN/1T5rncWLy1tc7SnmtZSzqnYrJzBtLxBvCJ9/+Q/G
            Xx9TCyPT/C/HvJ6J4InKP9Q3XNm41HhWgJeeCsR3d5Ar1L9e+PAStIeKXom+jzDp
            fLXEEq4iGGGq2JtHzl/u4rd4xmSvg7FFCrwc4FXs/SzohrPyeJXrO/LYyotiYLPU
            ZgEJAhWk+iEdNvwS7vy5lI8VCpJUO++fS4m87Fvrj870Az4UK5c9E3E4Y0LUNXOj
            C+hUVcnKt4Vv+/sQbj5jdszqef4rRIhzpp6JsJv8DtXD5LefAQAqk0UoHvLVDHlA
            bS2GdYTIvg==
            =HiVK
            -----END PGP MESSAGE-----
          fp: 8586714C9564B92FD2D6D41B6B14541D374F98EA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
