---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.1.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
  values:
    controller:
      ingressClass: nginx
      replicaCount: 3
      extraEnvs:
        - name: TZ
          value: "Europe/London"
      service:
        type: LoadBalancer
        loadBalancerIP: "${INGRESS_NGINX_LB}"
        externalTrafficPolicy: Local
      publishService:
        enabled: true
      ingressClassResource:
        default: true    
      config:
        ssl-protocols: "TLSv1.3 TLSv1.2"
        proxy-body-size: "100m"
        use-forwarded-headers: "true"
        custom-http-errors: >-
          401,403,404,500,501,502,503
        forwarded-for-header: "CF-Connecting-IP"
        client-header-timeout: 120
        client-body-buffer-size: "100M"
        client-body-timeout: 120
        enable-brotli: "true"
        hsts-max-age: "31449600"
        keep-alive: 120
        keep-alive-requests: 10000
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: networking
          namespaceSelector:
            any: true
        prometheusRule:
          enabled: true
      extraArgs:
        default-ssl-certificate: "networking/${SECRET_DOMAIN/./-}-tls"
      resources:
        requests:
          memory: 250Mi
          cpu: 100m
        limits:
          memory: 500Mi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
              app.kubernetes.io/component: controller
      podAnnotations:
        configmap.reloader.stakater.com/reload: "cloudflare-proxied-networks"
    defaultBackend:
      enabled: true
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 2.15.0
      replicaCount: 3
      extraEnvs:
        - name: TEMPLATE_NAME
          value: ghost
        - name: SHOW_DETAILS
          value: "false"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - ingress-nginx
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - default-backend
                topologyKey: kubernetes.io/hostname
  # valuesFrom:
  #   # Cloudflare Networks
  #   # https://www.cloudflare.com/ips/
  #   - kind: ConfigMap
  #     name: cloudflare-proxied-networks
  #     valuesKey: cloudflare-proxied-networks.txt
  #     targetPath: controller.config.proxy-real-ip-cidr
