apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - kube-system
  - monitoring
  - networking
  - flux-system
  - system-upgrade
  - home
  - media
  - metallb-system
#   - volsync
  