---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard-home-0
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: adguard-home
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: adguard/adguardhome
      tag: v0.108.0-b.3
      pullPolicy: Always

    persistence:
      config:
        enabled: true
        existingClaim: adguard-0-config-pvc

    env:
      TZ: "Europe/London"

    service:
      main:
        port:
          port: 3000

      dns:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${ADGUARD_LB}
        externalTrafficPolicy: Local
        ports:
          tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
          udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          ingress.kubernetes.io/whitelist-source-range: 192.168.167.0/24
          nginx.ingress.kubernetes.io/auth-url: https://auth.${SECRET_DOMAIN}/oauth2/auth
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/oauth2/start
        hosts:
          - host: "adguard.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "adguard.${SECRET_DOMAIN}"

    # nodeSelector:
    #   node-role.kubernetes.io/worker: "true"
    resources:
      requests:
        memory: 1000Mi
        cpu: 200m
      limits:
        memory: 2000Mi
