# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:kSZ8dOh1tqgv5Hx7LcarXxDlhVs3WwJ3eCXkkklcyHigL233lQ==,iv:fWkXtvj1QPlkLDYSJB+0BJ8dexNeBjCxphP32PVaz8k=,tag:/Wo6vJjV+aSCmDuItXpWGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaDY2VXMxOHZERjg4ZUda
            TFNhK0gyenZOZXYrTmFjSmJQRnp5QmZicEN3ClJvdTVWd1RLMFN3aWxnS2hHTHBM
            QVJzQWxHYk9qTW52MUtqZ0IxcFJYWDgKLS0tIDNOWTRRa1JrSGdKbTZQYTFYK3Ir
            aVZNVWFLeUhkQmlqV2xMaWtwL1JZNGsKi/TnCN5a+BjpiFtpoCCGQY/JSg1t+8oW
            MQMXSxGSzM09rtJ81Uv6UZan2PPBZAaAVE4A0WJ7BCBCM9T8FNgp9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-22T16:03:12Z"
    mac: ENC[AES256_GCM,data:zkI/9FFW+wOGQ+pt+uwoI3ip3diolO8MKeRUisdBomu9OqjPSFbIUzekYQEIMhZm9D6uW2AQxu0In5QLtOMMEhYmhPUUnJdAFi+UY1m3cJwhwCtgi8aMwOUn7MUph6Ot8sb/DLo4dOssRdfcxiWfuGe/VLsMullm1oIGrChMx3g=,iv:PzN4JhUgsHdwErkBn8IiIMMRDnoJ+1mOxD4RW9x13ug=,tag:9thpMQX+MnUmtAHtCUapoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
