---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: node-red
  namespace: home
spec:
  sourcePVC: node-red-pvc
  trigger:
    schedule: 0 2 * * *
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: node-red-restic-secret
    volumeSnapshotClassName: longhorn-snapshot-vsc
    storageClassName: longhorn-static
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 10
      within: 3d

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: node-red-restic-secret
  namespace: home
type: Opaque
stringData:
  RESTIC_REPOSITORY: s3:https://gateway.storjshare.io/home-cluster-backup/node-red
  RESTIC_PASSWORD: glowing-enlisted-fantasy
  AWS_ACCESS_KEY_ID: jvsptdh4kyrlzudttwd6btqejwca
  AWS_SECRET_ACCESS_KEY: j3qla7eh6joowrylzyx2rxse3mfreozk7vdmgfhwd6zdpgdadrb6a
  RESTIC_PACK_SIZE: "60"
