---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-n1
  resources:
    requests:
      storage: 128Mi
